// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalCookieEmailDao is internal type for wrapping internal DAO implements.
type internalCookieEmailDao = *internal.CookieEmailDao

// cookieEmailDao is the data access object for table cookie_email.
// You can define custom methods on it to extend its functionality as you wish.
type cookieEmailDao struct {
	internalCookieEmailDao
}

var (
	// CookieEmail is globally public accessible object for table cookie_email operations.
	CookieEmail = cookieEmailDao{
		internal.NewCookieEmailDao(),
	}
)

// Fill with you ideas below.
